from django.core.exceptions import ValidationError
from django.db import models


class PaginationStrategy(models.TextChoices):
    URL_PARAM = "url_param", "URL Parameter (?page=2)"
    CLICK_NEXT = "click_next", "Click Next Button (Playwright)"
    SCROLL = "scroll", "Infinite Scroll"


class LLMEngine(models.TextChoices):
    GPT_4O = "gpt-4o", "OpenAI GPT-4o"
    GPT_4O_MINI = "gpt-4o-mini", "OpenAI GPT-4o-Mini"
    CLAUDE_3_OPUS = "claude-3-opus", "Anthropic Claude 3 Opus"


class ScraperType(models.TextChoices):
    CCMA = "ccma", "CCMA (Playwright)"
    JUDICIARY = "judiciary", "Judiciary (Playwright)"
    LOTTO = "lotto", "National Lottery (Playwright)"
    SEDARPLUS = "sedarplus", "SEDAR+ (Playwright + Solver)"


class PipelineConfiguration(models.Model):
    """
    Stores the dynamic blueprint for a Coeus extraction pipeline.
    Airflow/Dagster will query this table to generate DAGs at runtime.
    """

    # ---------------------------------------------------------
    # Metadata & Scheduling
    # ---------------------------------------------------------
    name = models.CharField(
        max_length=255, unique=True, help_text="e.g., SEC 10-K Filings"
    )
    scraper_type = models.CharField(
        max_length=20,
        choices=ScraperType.choices,
        default=ScraperType.SEDARPLUS,
        help_text="The specific worker script to execute.",
    )
    industry = models.CharField(
        max_length=100, blank=True, help_text="e.g., Finance, Mining, Healthcare"
    )
    document_type = models.CharField(
        max_length=100, blank=True, help_text="e.g., Technical Report, Annual Report"
    )
    is_active = models.BooleanField(
        default=True, help_text="Uncheck to pause this pipeline in the orchestrator."
    )
    schedule_cron = models.CharField(
        max_length=50, default="0 0 * * *", help_text="Standard Cron syntax."
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # ---------------------------------------------------------
    # Phase 1: Ingestion Config (Playwright)
    # ---------------------------------------------------------
    start_url = models.URLField(help_text="The root URL for the crawler to begin.")
    target_css_selector = models.CharField(
        max_length=255,
        blank=True,
        help_text="CSS selector identifying the PDF download links (legacy/generic).",
    )
    target_css_selector_categories = models.CharField(
        max_length=255,
        blank=True,
        help_text="CSS selector for category links/buttons.",
    )
    target_css_selector_documents = models.CharField(
        max_length=255,
        blank=True,
        help_text="CSS selector for document links.",
    )
    allow_insecure_https = models.BooleanField(
        default=False, help_text="Ignore SSL errors in Playwright."
    )
    allow_insecure_requests = models.BooleanField(
        default=False, help_text="Ignore SSL errors in requests (urllib3)."
    )
    extraction_params = models.JSONField(
        default=dict,
        blank=True,
        help_text="Arbitrary key-value pairs for specific scraper logic (e.g., filter_keyword).",
    )
    pagination_strategy = models.CharField(
        max_length=20,
        choices=PaginationStrategy.choices,
        default=PaginationStrategy.CLICK_NEXT,
    )
    discovery_script = models.TextField(
        blank=True,
        null=True,
        help_text="The raw Python code generated by the Selector Lab.",
    )

    # -----------------------------------------
    # Phase 2: Extraction Config (LLM)
    # -----------------------------------------
    requires_extraction = models.BooleanField(
        default=True,
        help_text="Uncheck to skip LLM extraction (e.g., for raw document hoarding like CCMA).",
    )
    llm_engine = models.CharField(
        max_length=20, choices=LLMEngine.choices, default=LLMEngine.GPT_4O
    )
    pydantic_schema_name = models.CharField(
        max_length=100,
        blank=True,
        help_text="The exact name of the Python class in schemas.py to enforce.",
    )
    extraction_instructions = models.TextField(
        blank=True,
        null=True,
        help_text="Custom instructions for the LLM to guide extraction.",
    )

    # ---------------------------------------------------------
    # Phase 3: Loading Config (Postgres)
    # ---------------------------------------------------------
    target_table = models.CharField(
        max_length=100,
        blank=True,
        help_text="The database table where the structured data will be UPSERTed.",
    )

    def clean(self):
        """Custom validation to ensure data integrity before saving via the Django Admin."""
        if (
            not self.schedule_cron.replace(" ", "")
            .replace("*", "")
            .replace("-", "")
            .replace("/", "")
            .isdigit()
            and "*" not in self.schedule_cron
        ):
            # Basic pseudo-validation just to show you know how to hook into model cleaning
            raise ValidationError(
                {"schedule_cron": "Please enter a valid cron expression."}
            )

    def __str__(self):
        status = "🟢 Active" if self.is_active else "🔴 Paused"
        return f"{status} | {self.name} ({self.schedule_cron})"

    def to_blueprint(self) -> dict:
        """
        Serializes the model into the exact JSON dictionary format
        expected by the Airflow dynamic DAG generator.
        """
        return {
            "pipeline_id": self.name.lower().replace(" ", "_").replace("-", "_"),
            "name": self.name,
            "scraper_type": self.scraper_type,
            "is_active": self.is_active,
            "schedule": self.schedule_cron,
            "metadata": {
                "industry": self.industry,
                "document_type": self.document_type,
            },
            "phase_1_ingestion": {
                "start_url": self.start_url,
                "target_asset_selector": self.target_css_selector,
                "target_css_selector_categories": self.target_css_selector_categories,
                "target_css_selector_documents": self.target_css_selector_documents,
                "allow_insecure_https": self.allow_insecure_https,
                "allow_insecure_requests": self.allow_insecure_requests,
                "pagination_strategy": self.pagination_strategy,
            },
            "phase_2_extraction": {
                "requires_extraction": self.requires_extraction,
                "engine": self.llm_engine,
                "expected_schema": self.pydantic_schema_name,
                "extraction_instructions": self.extraction_instructions,
                "extraction_params": self.extraction_params,
            },
            "phase_3_loading": {"table_name": self.target_table},
        }
