FROM mcr.microsoft.com/playwright/python:v1.58.0-jammy

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /opt/dagster/app

RUN pip install \
    --upgrade pip\
    dagster \
    dagster-postgres \
    dagster-docker

COPY requirements-worker.txt .
RUN pip install --no-cache-dir -r requirements-worker.txt
RUN playwright install --with-deps chromium

RUN mkdir -p /app/data/scraped_pdfs

COPY dagster/definitions.py .

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]