# Generated by Django 4.2.29 on 2026-04-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False, 'verbose_name_plural': 'Companies'},
        ),
    ]
