# Generated by Django 4.2.30 on 2026-05-03 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0002_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(blank=True, help_text='e.g., Stock ticker or registration number.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'db_table': 'entities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_date', models.DateField()),
                ('record_type', models.CharField(help_text="e.g., 'Resource Estimate' or 'Financial Summary'", max_length=100)),
                ('data', models.JSONField(help_text='Industry-specific data extracted by the LLM.')),
                ('requires_human_review', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'extracted_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'targets',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='ResourceEstimate',
        ),
    ]
