# Generated by Django 6.0.7 on 2026-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0003_entity_extractedrecord_target_delete_asset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'managed': True, 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='extractedrecord',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='extractedrecord',
            name='cleaned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='extractedrecord',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='extractedrecord',
            name='status',
            field=models.CharField(choices=[('indexed', 'Indexed'), ('detailed', 'Detailed')], default='indexed', help_text='The status of the scraping workflow.', max_length=20),
        ),
        migrations.AlterField(
            model_name='extractedrecord',
            name='data',
            field=models.JSONField(help_text='Data extracted by the LLM.'),
        ),
        migrations.AlterField(
            model_name='extractedrecord',
            name='record_type',
            field=models.CharField(help_text="e.g., 'Case Law' or 'Financial Summary'", max_length=100),
        ),
        migrations.AlterField(
            model_name='extractedrecord',
            name='source_url',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='location',
            field=models.URLField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('entity', 'target_name')},
        ),
    ]
