# Generated by Django 6.0.7 on 2026-07-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0004_alter_entity_options_alter_extractedrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedrecord',
            name='requires_human_review',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
