# Generated by Django 6.0.7 on 2026-07-30 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extracted_data", "0005_alter_extractedrecord_requires_human_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractedrecord",
            old_name="processed_at",
            new_name="detailed_at",
        ),
        migrations.RenameField(
            model_name="extractedrecord",
            old_name="extracted_at",
            new_name="scraped_at",
        ),
        migrations.CreateModel(
            name="ScrubbedRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(help_text="Cleaned JSON data (PII removed)."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extracted_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrubbed_records",
                        to="extracted_data.extractedrecord",
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "scrubbed_records",
                "managed": True,
            },
        ),
    ]
