# Generated by Django 6.0.7 on 2026-07-31 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0006_rename_processed_at_extractedrecord_detailed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrubbedrecord',
            name='extracted_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrubbed_record', to='extracted_data.extractedrecord'),
        ),
    ]
