# Generated by Django 6.0.7 on 2026-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0007_alter_scrubbedrecord_extracted_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedrecord',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='extractedrecord',
            name='status',
            field=models.CharField(choices=[('indexed', 'Indexed'), ('detailed', 'Detailed')], db_index=True, default='indexed', help_text='The status of the scraping workflow.', max_length=20),
        ),
    ]
