# Generated by Django 6.0.7 on 2026-08-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0008_alter_extractedrecord_scraped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedrecord',
            name='detailed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
