# Generated by Django 6.0.7 on 2026-08-04 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extracted_data", "0009_alter_extractedrecord_detailed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookStackImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bookstack_page_id",
                    models.IntegerField(help_text="ID of the created BookStack page."),
                ),
                (
                    "bookstack_book_id",
                    models.IntegerField(
                        help_text="ID of the destination BookStack book."
                    ),
                ),
                ("court_name", models.CharField(db_index=True, max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "scrubbed_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookstack_import",
                        to="extracted_data.scrubbedrecord",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "BookStack Imports",
                "db_table": "bookstack_imports",
                "managed": True,
            },
        ),
    ]
