# Generated by Django 6.0.7 on 2026-08-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0009_alter_extractedrecord_detailed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.CharField(blank=True, help_text='Category of target (e.g., cases, gaz, journals, other).', max_length=50, null=True),
        ),
    ]
