# Generated by Django 5.2.17 on 2026-08-15 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0010_target_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='Parsed document sections data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_record', to='extracted_data.extractedrecord')),
            ],
            options={
                'db_table': 'parsed_records',
                'managed': True,
            },
        ),
    ]
