# Generated by Django 5.2.17 on 2026-08-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracted_data', '0011_parsedrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractedrecord',
            old_name='cleaned_at',
            new_name='scrubbed_at',
        ),
        migrations.AlterField(
            model_name='extractedrecord',
            name='scrubbed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedrecord',
            name='parsed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='parsedrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrubbedrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
