# Generated by Django 4.2.29 on 2026-04-07 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('classification', models.CharField(max_length=50)),
                ('commodity', models.CharField(max_length=50)),
                ('tonnage_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grade_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_estimates',
                'managed': False,
            },
        ),
    ]
