tls:
  certificates:
    - certFile: /etc/letsencrypt/live/8ohm.co.za/fullchain.pem
      keyFile: /etc/letsencrypt/live/8ohm.co.za/privkey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/live/8ohm.co.za/fullchain.pem
        keyFile: /etc/letsencrypt/live/8ohm.co.za/privkey.pem
