# Generated by Django 4.2.29 on 2026-04-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Glencore SEDAR Filings', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause this pipeline in the orchestrator.')),
                ('schedule_cron', models.CharField(default='0 0 * * *', help_text='Standard Cron syntax.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_url', models.URLField(help_text='The root URL for the crawler to begin.')),
                ('llm_engine', models.CharField(choices=[('gpt-4o', 'OpenAI GPT-4o'), ('gpt-4o-mini', 'OpenAI GPT-4o-Mini'), ('claude-3-opus', 'Anthropic Claude 3 Opus')], default='gpt-4o', max_length=20)),
                ('pydantic_schema_name', models.CharField(default='NI43101ReportExtraction', help_text='The exact name of the Python class in schemas.py to enforce.', max_length=100)),
                ('target_table', models.CharField(default='resource_estimates', help_text='The database table where the structured data will be UPSERTed.', max_length=100)),
            ],
        ),
    ]
