# Generated by Django 4.2.30 on 2026-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_alter_pipelineconfiguration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='discovery_script',
            field=models.TextField(blank=True, help_text='The raw Python code generated by the Selector Lab.', null=True),
        ),
    ]
