# Generated by Django 4.2.30 on 2026-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_pipelineconfiguration_discovery_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='requires_extraction',
            field=models.BooleanField(default=True, help_text='Uncheck to skip LLM extraction (e.g., for raw document hoarding like CCMA).'),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='pydantic_schema_name',
            field=models.CharField(blank=True, default='NI43101ReportExtraction', help_text='The exact name of the Python class in schemas.py to enforce.', max_length=100),
        ),
    ]
