# Generated by Django 4.2.29 on 2026-05-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipelineconfiguration_requires_extraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='document_type',
            field=models.CharField(blank=True, help_text='e.g., Technical Report, Annual Report', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='extraction_instructions',
            field=models.TextField(blank=True, help_text='Custom instructions for the LLM to guide extraction.', null=True),
        ),
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g., Finance, Mining, Healthcare', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='name',
            field=models.CharField(help_text='e.g., SEC 10-K Filings', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='pydantic_schema_name',
            field=models.CharField(blank=True, help_text='The exact name of the Python class in schemas.py to enforce.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='target_table',
            field=models.CharField(blank=True, help_text='The database table where the structured data will be UPSERTed.', max_length=100),
        ),
    ]
