# Generated by Django 4.2.29 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_pipelineconfiguration_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='allow_insecure_https',
            field=models.BooleanField(default=False, help_text='Ignore SSL errors in Playwright.'),
        ),
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='allow_insecure_requests',
            field=models.BooleanField(default=False, help_text='Ignore SSL errors in requests (urllib3).'),
        ),
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='extraction_params',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value pairs for specific scraper logic (e.g., filter_keyword).'),
        ),
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='target_css_selector_categories',
            field=models.CharField(blank=True, help_text='CSS selector for category links/buttons.', max_length=255),
        ),
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='target_css_selector_documents',
            field=models.CharField(blank=True, help_text='CSS selector for document links.', max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='target_css_selector',
            field=models.CharField(blank=True, help_text='CSS selector identifying the PDF download links (legacy/generic).', max_length=255),
        ),
    ]
