# Generated by Django 4.2.29 on 2026-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_pipelineconfiguration_allow_insecure_https_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='scraper_type',
            field=models.CharField(choices=[('ccma', 'CCMA (Playwright)'), ('judiciary', 'Judiciary (Playwright)'), ('lotto', 'National Lottery (Playwright)'), ('sedarplus', 'SEDAR+ (Playwright + Solver)')], default='sedarplus', help_text='The specific worker script to execute.', max_length=20),
        ),
    ]
