# Generated by Django 4.2.30 on 2026-05-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_alter_pipelineconfiguration_scraper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='scraper_type',
            field=models.CharField(choices=[('ccma_playwright', 'CCMA (Playwright)'), ('judiciary', 'Judiciary (Playwright)'), ('lotto', 'National Lottery (Playwright)'), ('sedarplus', 'SEDAR+ (Playwright + Solver)'), ('mantech', 'Mantech (Playwright)')], default='sedarplus', help_text='The specific worker script to execute.', max_length=20),
        ),
    ]
