# Generated by Django 4.2.30 on 2026-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_alter_pipelineconfiguration_scraper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='llm_engine',
            field=models.CharField(choices=[('gemini-cli', 'Gemini Cli')], default='gemini-cli', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='scraper_type',
            field=models.CharField(choices=[('ccma_playwright', 'CCMA (Playwright)'), ('judiciary', 'Judiciary (Playwright)'), ('lotto', 'National Lottery (Playwright)'), ('sedarplus', 'SEDAR+ (Playwright + Solver)'), ('mantech', 'Mantech (Playwright)'), ('livestainable', 'Livestainable (Playwright)')], default='sedarplus', help_text='The specific worker script to execute.', max_length=20),
        ),
    ]
