# Generated by Django 4.2 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0013_alter_pipelineconfiguration_scraper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='use_proxy',
            field=models.BooleanField(
                default=False,
                help_text='Route all scraper traffic through the rotating Webshare proxy.',
            ),
        ),
    ]
