# Generated by Django 6.0.6 on 2026-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0014_pipelineconfiguration_use_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineconfiguration',
            name='discovery_script',
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='allow_insecure_https',
            field=models.BooleanField(default=True, help_text='Ignore SSL errors in Playwright.'),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='allow_insecure_requests',
            field=models.BooleanField(default=True, help_text='Ignore SSL errors in requests (urllib3).'),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('html', 'HTML / JSON')], default='pdf', help_text='The primary document type that the LLM extractor will read.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='llm_engine',
            field=models.CharField(choices=[('ollama/phi4-mini', 'Local Phi-4 Mini (Ollama)')], default='ollama/phi4-mini', help_text='The AI model used for extraction (Ollama model string).', max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='requires_extraction',
            field=models.BooleanField(default=True, help_text='Uncheck to skip LLM extraction (e.g., for raw document hoarding - NOTE: stores PDF/JSON on local filesystem).'),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='schedule_cron',
            field=models.CharField(default='0 0 * * *', help_text='Midnight - Standard Cron syntax.', max_length=50),
        ),
    ]
