# Generated by Django 6.0.6 on 2026-06-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0015_remove_pipelineconfiguration_discovery_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='scraper_type',
            field=models.CharField(choices=[('ccma_playwright', 'CCMA (Playwright)'), ('judiciary', 'Judiciary (Playwright)'), ('lotto', 'National Lottery (Playwright)'), ('sedarplus', 'SEDAR+ (Playwright + Solver)'), ('mantech', 'Mantech (Playwright)'), ('livestainable', 'Livestainable (Playwright)'), ('sabinet', 'Sabinet (Playwright)'), ('sabinet_detail', 'Sabinet Details (Playwright)'), ('saflii', 'SAFLII (Basic)'), ('new_saflii', 'New SAFLII')], default='sedarplus', help_text='The specific worker script to execute.', max_length=20),
        ),
    ]
