# Generated by Django 6.0.6 on 2026-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0016_alter_pipelineconfiguration_scraper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='scraper_type',
            field=models.CharField(choices=[('lotto', 'National Lottery (Playwright)'), ('sedarplus', 'SEDAR+ (Playwright + Misstcha)'), ('mantech', 'Mantech (Playwright)'), ('livestainable', 'Livestainable (Playwright)'), ('sabinet', 'Sabinet (Playwright + Misstcha)'), ('new_saflii', 'SAFLII (BeautifulSoup + AI)')], default='sedarplus', help_text='The specific worker script to execute.', max_length=20),
        ),
    ]
