# Generated by Django 6.0.6 on 2026-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0017_alter_pipelineconfiguration_scraper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='pipeline_state',
            field=models.JSONField(blank=True, default=dict, help_text='Scraper progress state (e.g., last_year/last_month for rolling-window scrapers). Managed automatically.'),
        ),
        migrations.AddField(
            model_name='pipelineconfiguration',
            name='subset',
            field=models.CharField(blank=True, help_text="Subset label used as the Target name for scraped records (e.g., 'CCMA Awards', 'ZACC').", max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('json', 'JSON Document'), ('html', 'HTML')], default='json', help_text='The primary document type that will be scraped. e.g. PDF, JSON or sometimes plain HTML', max_length=10),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to pause this pipeline in Dagster.'),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='name',
            field=models.CharField(help_text='e.g., Saflii', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='scraper_type',
            field=models.CharField(choices=[('lotto', 'National Lottery (Playwright)'), ('sedarplus', 'SEDAR+ (Playwright + Misstcha)'), ('mantech', 'Mantech (Playwright)'), ('livestainable', 'Livestainable (Playwright)'), ('sabinet', 'Sabinet (Playwright + Misstcha)'), ('new_saflii', 'SAFLII (BeautifulSoup + AI)')], default='new_saflii', help_text='The specific worker script to execute.', max_length=20),
        ),
    ]
