# Generated by Django 6.0.7 on 2026-07-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0018_remove_pipelineconfiguration_pagination_strategy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingPipelineMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pipeline_name",
                    models.CharField(
                        help_text="The pipeline name or identifier.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Calculated metrics including average scrape rate, uptime, and worker breakdown.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scraping Pipeline Metrics",
                "verbose_name_plural": "Scraping Pipeline Metrics",
            },
        ),
    ]
