# Generated by Django 6.0.7 on 2026-07-23 20:33

import django.db.models.deletion
import pipelines.models
from django.db import migrations, models


def seed_choices(apps, schema_editor):
    DocumentType = apps.get_model("pipelines", "DocumentType")
    LLMEngine = apps.get_model("pipelines", "LLMEngine")
    ScraperType = apps.get_model("pipelines", "ScraperType")

    # Document types
    document_types_data = {
        "pdf": "PDF Document",
        "json": "JSON Document",
        "html": "HTML",
    }
    for name, label in document_types_data.items():
        DocumentType.objects.get_or_create(name=name, defaults={"label": label})

    # LLM engines
    llm_engines_data = {
        "ollama/phi4-mini": "Local Phi-4 Mini (Ollama)",
    }
    for name, label in llm_engines_data.items():
        LLMEngine.objects.get_or_create(name=name, defaults={"label": label})

    # Scraper types
    scraper_types_data = {
        "lotto": "National Lottery (Playwright)",
        "sedarplus": "SEDAR+ (Playwright + Misstcha)",
        "mantech": "Mantech (Playwright)",
        "livestainable": "Livestainable (Playwright)",
        "sabinet": "Sabinet (Playwright + Misstcha)",
        "new_saflii": "SAFLII (BeautifulSoup + AI)",
    }
    for name, label in scraper_types_data.items():
        ScraperType.objects.get_or_create(name=name, defaults={"label": label})


def migrate_data_to_foreign_keys(apps, schema_editor):
    PipelineConfiguration = apps.get_model("pipelines", "PipelineConfiguration")
    DocumentType = apps.get_model("pipelines", "DocumentType")
    LLMEngine = apps.get_model("pipelines", "LLMEngine")
    ScraperType = apps.get_model("pipelines", "ScraperType")

    for config in PipelineConfiguration.objects.all():
        # Get or create referenced objects if they don't exist
        doc_type_val = getattr(config, "document_type_old", None) or "json"
        doc_type_obj, _ = DocumentType.objects.get_or_create(
            name=doc_type_val,
            defaults={"label": doc_type_val.upper()}
        )
        config.document_type = doc_type_obj

        llm_engine_val = getattr(config, "llm_engine_old", None) or "ollama/phi4-mini"
        llm_engine_obj, _ = LLMEngine.objects.get_or_create(
            name=llm_engine_val,
            defaults={"label": llm_engine_val}
        )
        config.llm_engine = llm_engine_obj

        scraper_type_val = getattr(config, "scraper_type_old", None) or "new_saflii"
        scraper_type_obj, _ = ScraperType.objects.get_or_create(
            name=scraper_type_val,
            defaults={"label": scraper_type_val}
        )
        config.scraper_type = scraper_type_obj

        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0019_scrapingpipelinemetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The programmatic identifier (e.g., 'pdf', 'json').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-friendly name (e.g., 'PDF Document').",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The programmatic identifier (e.g., 'ollama/phi4-mini').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-friendly name (e.g., 'Local Phi-4 Mini (Ollama)').",
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScraperType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The programmatic identifier (e.g., 'lotto', 'new_saflii').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-friendly name (e.g., 'National Lottery (Playwright)').",
                        max_length=150,
                    ),
                ),
            ],
        ),
        migrations.RunPython(seed_choices),
        migrations.RenameField(
            model_name="pipelineconfiguration",
            old_name="document_type",
            new_name="document_type_old",
        ),
        migrations.RenameField(
            model_name="pipelineconfiguration",
            old_name="llm_engine",
            new_name="llm_engine_old",
        ),
        migrations.RenameField(
            model_name="pipelineconfiguration",
            old_name="scraper_type",
            new_name="scraper_type_old",
        ),
        migrations.AddField(
            model_name="pipelineconfiguration",
            name="document_type",
            field=models.ForeignKey(
                default=pipelines.models.get_default_document_type,
                help_text="The primary document type that will be scraped. e.g. PDF, JSON or sometimes plain HTML",
                on_delete=django.db.models.deletion.PROTECT,
                to="pipelines.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfiguration",
            name="llm_engine",
            field=models.ForeignKey(
                default=pipelines.models.get_default_llm_engine,
                help_text="The AI model used for extraction (Ollama model string).",
                on_delete=django.db.models.deletion.PROTECT,
                to="pipelines.llmengine",
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfiguration",
            name="scraper_type",
            field=models.ForeignKey(
                default=pipelines.models.get_default_scraper_type,
                help_text="The specific worker script to execute.",
                on_delete=django.db.models.deletion.PROTECT,
                to="pipelines.scrapertype",
            ),
        ),
        migrations.RunPython(migrate_data_to_foreign_keys),
        migrations.RemoveField(
            model_name="pipelineconfiguration",
            name="document_type_old",
        ),
        migrations.RemoveField(
            model_name="pipelineconfiguration",
            name="llm_engine_old",
        ),
        migrations.RemoveField(
            model_name="pipelineconfiguration",
            name="scraper_type_old",
        ),
    ]
