# Generated by Django 5.2.17 on 2026-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0020_documenttype_llmengine_scrapertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineconfiguration',
            name='pydantic_schema_name',
            field=models.CharField(blank=True, help_text='The exact name of the Python class in extraction_workers/schemas to enforce.', max_length=100),
        ),
    ]
